apiVersion: v1
kind: Service
metadata:
  name: key-value-pair-app-service
spec:
  selector:
    app: key-value-pair-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
