version: '3.8'

services:
  webapp:
    image: unclejohn420/camb_ai_backend_key_value_app
    container_name: web-app
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
